modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"
issueTrackerURL = "https://github.com/NovaMachina-Mods/ExNihiloTinkers/issues" #optional
[[mods]] #mandatory
modId="exnihilotinkers" #mandatory
version="1.0.0" #mandatory
displayName="Ex Nihilo Sequentia - Tinkers Addon" #mandatory
#displayURL = "${curseforge_url}" #optional
logoFile = "logo.png" #optional
#authors="${mod_authors}" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''${mod_description}'''
[[dependencies.exnihilotinkers]] #optional
modId = "exnihilosequentia"
mandatory = false
versionRange = "${ex_nihilo_version}"
ordering = "AFTER"
side = "BOTH"
[[dependencies.exnihilotinkers]] #optional
modId = "tconstruct"
mandatory = true
versionRange = "${tinkers_version}"
ordering = "AFTER"
side = "BOTH"
