modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"
issueTrackerURL = "${git_url}/issues" #optional
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL = "${curseforge_url}" #optional
logoFile = "logo.png" #optional
authors="${mod_authors}" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''${mod_description}'''
[[dependencies.${mod_id}]] #optional
modId = "exnihilosequentia"
mandatory = true
versionRange = "${ex_nihilo_version}"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]] #optional
modId = "tconstruct"
mandatory = true
versionRange = "${tinkers_version}"
ordering = "AFTER"
side = "BOTH"
